### ISSUE TITLE
Running Initialize UiPath Code Support for this project Command

### ISSUE THREAD

**Issue by giogog** [automationcodex/vscode-uipath-code-support#1]
After I install this extension and Run Command "Initialize UiPath Code Support for this project" with ctrl+shift+p, this error comes ERROR: The system was unable to find the specified registry key or value

**Comment by timmorrisxyz** [comment]
I am also getting this error.

**Comment by automationcodex** [comment]
Hi!

Thank you for bringing this issue to my attention. Normally, the extension locates the UiPath installation folder by checking the registry. However, the registry key may not be present for some installation types.

With the latest version (1.2.0), I have added the option to specify the UiPath installation folder manually. To do this:

- Set the "useCustomUipathInstallationFolder" setting to `true`.
- Enter the UiPath installation folder path in the "uipathInstallationFolder" setting.

I hope this helps!
